terascope/standard-assets

asset/asset.json, asset/package.json, asset/src/field_router/processor.ts, asset/src/field_router/schema.ts, package.json, test/fields_router/processor-spec.ts
field_router
- Added include_field_names option to control if field names are include in route. 
- Defaults to true
=> Field router add include field names

asset/asset.json, asset/package.json, asset/src/routed_sender/schema.ts, docs/operations/routed_sender.md
Bumped the routed_sender's size default property to 10k.  Not sure if there was a reason it was only 500, but in using this with the kafka_api the default value caused issues.  Also 10K is a typical value for the es sender size and since the router_senders values overwrites the size settings in the api I think that 10k makes more sense as a default size setting here.
Also bumped the asset version to 0.12.1
=> bumped the routed senders default size to 10k

asset/asset.json, asset/package.json, package.json
* bumped asset version to 0.12.2
* indicates change to how the bundled asset is built, which fixes transforms op issues in the bundled asset
=> bumped asset version 

asset/asset.json, asset/package.json, asset/src/date_router/processor.ts, asset/src/date_router/schema.ts, docs/operations/date_router.md, package.json, test/date_router/processor-spec.ts, test/date_router/schema-spec.ts
changes to routed_sender:
* changed delimiter names to `date_delimiter` and `date_unit_delimiter` to communicate where the delimiters are applied, this is a breaking change from past versions
* set the delimiter defaults to reflect common use cases
* added delimiter limitations and validation - only `/`, `-`, `_`, `.`, or empty quotes (no delimiter) are available to be used as delimiters
* updated documentation
* bumped asset to version 0.13.0
=> routed_sender: delimiter validation, schema delimiter name changes, expanded tests, updated documentation

asset/asset.json, asset/package.json, asset/src/key_router/schema.ts, docs/operations/key_router.md, package.json, packages/standard-asset-apis/package.json, packages/standard-asset-apis/src/routers/KeyRouter.ts, packages/standard-asset-apis/test/routers/KeyRouter-spec.ts
- Added option `suffix_use` to append a suffix to the routing key
- Added optional suffix values for `suffix_upper`, `suffix_lower`, `suffix_number`, and `suffix_other`
- Example to only append a suffix for uppercase routing keys
```json
{
"_op": "key_router",
"use": 1
"from": "beginning",
"suffix_use": true,
"suffix_upper": "--u",
} 
```
- Example to only append suffixes for all routing keys
```json
{
"_op": "key_router",
"use": 1
"from": "beginning",
"suffix_use": true,
"suffix_upper": "--u",
"suffix_lower": "--l",
"suffix_number": "--n",
"suffix_other":  "--c"
} 
```
refs #373
=> Added support for appending a suffix to the key route in the KeyRouter

asset/asset.json, asset/package.json, asset/src/add_key/processor.ts, package.json, test/add_key/processor-spec.ts
* fixed bug where adding a field value that is an object to the key string before it's hashed isn't [object object] but a sorted parsed string of the objects keys and values
* added test
* bumped asset version
=> add_key nested object fix

asset/package.json, package.json, packages/standard-asset-apis/package.json, yarn.lock
The following packages were upgraded:
- ts-transforms                               0.71.0 => 0.76.0
- @terascope/scripts                     0.58.0 => 0.59.0
- @terascope/utils                          0.46.0 => 0.51.0
- @terascope/job-components    0.59.0 => 0.64.0
=> Upgrade ts-transforms, utils, job-components, etc.

asset/package.json, asset/src/data_generator/fetcher.ts, package.json, yarn.lock
I've updated the dependency ```mock-data-generator``` to ```v3.0.3``` from ```v2.12.0```
Here are dependencies that got added to the assets package.json to be compatible with the new major version of mock-data-generator.
- ```@faker-js/faker@v8.1.0```
- ```@types/chance@v1.1.4```
- ```chance@v1.1.11```
- ```randexp@0.5.3```
The reason is because mock-data-generator now has you bring in your own 3rd party generators instead of having them built in. So I had to install all the generators that we were utilizing previously and use the new ```addGenerator()``` method to the ```mocker()``` function to get it to work correctly. 
Diff[ Link](https://github.com/terascope/standard-assets/compare/master...update-data-generator#diff-5f4dc783289d20bf2647fe9e38f18d9a8828050fa2e563bd990fef8ed145c834) …
=> Bump mock-data-generator to v3.0.3

asset/asset.json, asset/package.json, package.json, packages/standard-asset-apis/package.json, yarn.lock
Bump standard-asset-apis to 0.6.2 - this should have been done when @terascope/utils was updated.
Bump standard-asset to 0.22.3
Update dependencies:
```
Package             Current Wanted  Workspace                      Package Type 
@types/chance       1.1.5   1.1.6   standard                       dependencies    
@types/express      4.17.20 4.17.21 standard-assets-bundle         devDependencies 
@types/express      4.17.20 4.17.21 standard                       dependencies    
@types/jest         29.5.7  29.5.8  standard-assets-bundle         devDependencies 
@types/jest         29.5.7  29.5.8  @terascope/standard-asset-apis devDependencies 
@types/json2csv     5.0.5   5.0.6   standard-assets-bundle         devDependencies 
@types/node         18.18.7 18.18.9 standard-assets-bundle …
```
=> Update dependencies, bump standard-asset-apis and standard-asset

asset/src/data_generator/data-schema.ts
- Changed faker dependency to use `string.uuid` instead of `datatype.uuid` to fix deprecation warning cluttering worker logs. 
- This is specific to workers that are running `data_generator` operations.
This is a fix to issue #767
=> Update deprecated method in faker dependency

asset/package.json, package.json, packages/standard-asset-apis/package.json, yarn.lock
@terascope/scripts from 0.72.2 to 0.73.0
@terascope/job-components from 0.68.0 to 0.69.0
@terascope/utils from 0.55.0 to 0.56.0
ts-transform from 0.81.0 to 0.82.0
=> Bundled dependency update - scripts, job-components, ts-transforms, utils

asset/asset.json, asset/package.json, asset/src/count_by_field/processor.ts, package.json, packages/standard-asset-apis/package.json, test/count_by_field/processor-spec.ts, yarn.lock
- adds a static object `counters` to `CountByField` to track all field counts across multiple operations
- add default labels from worker to `count_by_field_count_total` metric
- `addCounter` now uses a `collect()` function to increment count only at time of `/metrics` endpoint scrape 
- `_incMetric` now increments its value in `counters` instead of the `promMetrics` directly
- tests that use `promMetrics` now manually init the API
- tests use `test.context.apis.scrapePromMetrics()` to get metrics directly from `prom-client`
=> update promMetrics interface and use collect fn

asset/asset.json, asset/package.json, asset/src/count_by_field/processor.ts, package.json, yarn.lock
- Introduces backwards compatibility for teraslice versions before `v1.4.0`
- This fixes an issue where using a teraslice version older than version `v1.4.0` would throw `TypeError: this.promMetrics.addGauge is not a function`
- Bump **standard-assets** to `v0.25.1`
- Updates the following dependencies:
- **@terascope/job-components** from `v0.74.2` to `v0.75.0`
ref: https://github.com/terascope/teraslice/issues/3625
=> Backwards compatibility fix for teraslice 

.yarnclean, asset/package.json, package.json, packages/standard-asset-apis/package.json, yarn.lock
- Remove `images` from `.yarnclean` - this removes any directory with that name from `node_modules`
- Update `scripts` from 0.78.0 to 0.81.0
- Update `ts-transforms` from 0.85.3 to 0.86.0
- Update `teraslice-test-harness` from 1.0.1 to 1.1.0
- Update `job-components` from 1.0.1 to 1.1.0
- Update `utils` from 0.59.3 to 0.60.0
=> Yarnclean fix and dependency updates

.github/workflows/build-and-publish-asset.yml, .github/workflows/test-asset.yml, package.json, scripts/docker-limit-check.sh, yarn.lock
- Update workflows pinned hash
- Update scripts from 0.81.2 to 0.83.1
- Add `docker-limit-check.sh` script
- Add docker related scripts to `package.json`
=> Update workflows and scripts, make compatible with caching

asset/asset.json, asset/package.json, package.json, packages/standard-asset-apis/package.json, yarn.lock
- bump standard-assets from 1.0.0 to 1.0.1
- bump standard-asset-apis from 0.7.2 to 1.0.0 ( this should have been done when we updated to ESM)
- update job-components from 1.1.0 to 1.2.0
- update utils from 0.60.0 to 1.0.0
- update ts-transforms from 0.86.1 to 1.0.3
- update scripts from 0.83.3 to 1.0.0
- update teraslice-test-harness from 1.1.0 to 1.2.0
=> Bundled dependency updates

.github/workflows/build-and-publish-asset.yml, .github/workflows/test-asset.yml
This PR updates the github workflows hash to incorporate a fix for the upload-artifact@v4 action during build-and-publish-asset.yml workflow
=> udpate workflow hash

asset/asset.json, asset/package.json, package.json, packages/standard-asset-apis/package.json, yarn.lock
- Call `ts-scripts test` instead of `jest` in all test scripts for `standard-asset-apis`
- Add `@terascope/scripts` as a dev dependency to `standard-asset-apis`
- Bump `@terascope/scripts` from 1.0.0 to 1.0.1
- Bump `standard-asset-apis` from 1.0.0 to 1.0.1
- Bump `standard-assets` from 1.0.1 to 1.0.2
- Remove `NODE_OPTIONS='--experimental-vm-modules'` from test scripts - it is built into ts-scripts now
=> Use ts-scripts test-runner for testing standard-asset-apis

asset/asset.json, asset/package.json, asset/src/data_generator/fetcher.ts, asset/src/data_generator/schema.ts, docs/operations/data_generator.md, package.json, test/data-generator/schema-spec.ts, yarn.lock
- Adds new `delay` option to the `data_generator` operation 
- This option allows the user to specify how long it will take for the worker to complete its slice.
- _Example:_ If **delay** is set to `60` and **size** is set to `10000` with only 1 worker, the job will generate 10,000 records per minute approximately. You can achieve about the same record output with more slices by decreasing size and decreasing delay.
- Bumps **standard-assets** from `v1.0.3` to `1.1.0`
- Updated docs to include use case and description for `delay` param in `data_generator`
#898
=> Add delay option to data_generator operation

asset/package.json, package.json, packages/standard-asset-apis/package.json, test/count_by_field/processor-spec.ts, yarn.lock
- bump job-components from 1.4.0 to 1.5.0
- bump scripts from 1.3.2 to 1.4.0
- bump ts-transforms from 1.2.0 to 1.3.0
- bump utils from 1.1.0 to 1.3.0
- change `test/count_by_field/processor-spec.ts` `promMetrics.init()` config to include required field `prom_metrics_display_url`
=> Bundles dependency updates

asset/asset.json
- Adds a `minimum teraslice version` in the asset.json
- This will help teraslice determine if the asset is compatible
=> Add minimum_teraslice_version info to asset.json

asset/asset.json, asset/package.json, package.json, packages/standard-asset-apis/package.json
- bump standard-asset-apis from v1.0.2 to v1.03
- bump standard-assets from v1.2.0 to v1.3.0
=> Bump version for release

asset/asset.json, asset/package.json, asset/src/sample_random/processor.ts, docs/operations/sample_random.md, package.json, test/sample_random/processor-spec.ts
- Fixes a bug in the `sample_random` processor when `probability_to_keep` is set to 0%. If the random number generator returns 0 then a record would be returned ( 0 <= 0 is true ). Setting the `random()` function's minimum value to 1 ensures that no records will ever be returned ( 1 <= 0 is false).
- Update docs
- Add test with large dataset and `probability_to_keep` set to 0%
- bump standard asset from v1.3.1 to v1.3.2
ref: #988
=> fix bug in sample_random when probability_to_keep is 0

.github/workflows/build-and-publish-asset.yml, .github/workflows/test-asset.yml
This PR updates all github workflow calls to the `workflows` repo to now use main instead of a specific hash.
=> remove hash from reusable workflow calls

asset/asset.json, asset/package.json, package.json, packages/standard-asset-apis/package.json, yarn.lock
This PR updates the following packages:
- dependencies
- @terascope/data-mate from 1.7.7 to 1.7.8
- @terascope/job-components from 1.9.7 to 1.9.8
- @terascope/standard-asset-apis from 1.0.3 to 1.0.4
- @terascope/teraslice-state-storage from 1.8.4 to 1.8.5
- @terascope/utils from 1.7.6 to 1.7.7
- ts-transforms from 1.7.7 to 1.7.8
- devDependencies
- @terascope/eslint-config from 1.1.9 to 1.1.10
- @terascope/job-components from 1.9.7 to 1.9.8
- @terascope/scripts from 1.12.0 to 1.13.0
- @terascope/standard-asset-apis from 1.0.3 to 1.0.4
- dependencies
- @terascope/utils from 1.7.6 to 1.7.7"
- devDependencies
- @terascope/scripts from 1.12.0 to 1.13.0
=> bundled dependency updates 3-17-2025

asset/package.json, package.json, packages/standard-asset-apis/package.json, yarn.lock
This PR updates the following packages:
- dependencies
- @faker-js/faker from 9.6.0 to 9.7.0
- devDependencies
- @terascope/scripts from 1.15.1 to 1.15.2
- @types/node from 22.14.0 to 22.14.1
- ts-jest from 29.3.1 to 29.3.2
- typescript from 5.8.2 to 5.8.3
- devDependencies
- @terascope/scripts from 1.15.1 to 1.15.2
- @types/node from 22.14.0 to 22.14.1
- ts-jest from 29.3.1 to 29.3.2
- typescript from 5.8.2 to 5.8.3
=> bundled dependency updates for 4-14-2025

asset/asset.json, asset/package.json, package.json, website/docusaurus.config.js, website/src/pages/help.js
- adds `contextualSearch: false` to the algolia settings, which was defaulting to true and preventing the whole website from being searched.
- a few links on the help page are corrected
- Bump asset version from v1.3.5 to 1.3.6
=> [website] fix algolia doc search, correct links on help page

package.json, packages/standard-asset-apis/package.json, yarn.lock
This PR updates the following dependencies:
- @terascope/eslint-config: `v1.1.13`
- @terascope/scripts: `v1.15.4`
- eslint: `v9.25.0`
- @terascope/scripts: `v1.15.4`
=> bundled deps 2025-04-21

README.md, asset/asset.json, asset/package.json, package.json
Release 1.4.1 failed to build docs because of an illegal character in README.md. This PR fixes the README.md and bumps the asset to v1.4.1 to build the docs again.
=> fix illegal character in readme

jest.config.js, package.json, packages/standard-asset-apis/jest.config.js, packages/standard-asset-apis/package.json, tsconfig.json, yarn.lock
- updates the following packages:
- devDependencies
- @types/node from 24.5.2 to 24.7.0
- eslint from 9.36.0 to 9.37.0
- typescript from 5.9.2 to 5.9.3
- devDependencies
- @types/node from 24.5.2 to 24.7.0
- typescript from 5.9.2 to 5.9.3
- clear test warnings:
- move `isolatedModules` from jest.config.js to tsconfig.json
=> bundled dependency updates for 10-6-2025
