asset/asset.json
asset/package.json
asset/sorted_bucket_accumulator/processor.js
asset/yarn.lock
package.json
test/sorted_accumulator-spec.js
test/sorted_bucket_accumulator-spec.js
yarn.lock

use setImmediate in sorted_bucket_accumulator

v0.0.6 break out of event loop when sorting

---

asset/__lib/data-window.js
asset/accumulate/processor.js
asset/accumulate/schema.js
asset/accumulate_by_key/processor.js
asset/accumulate_by_key/schema.js
asset/asset.json
asset/data_window_to_array/processor.js
asset/data_window_to_array/schema.js
asset/dedup_by/processor.js
asset/dedup_by/schema.js
asset/group_by/processor.js
asset/group_by/schema.js
asset/package.json
asset/remove_key/processor.js
asset/remove_key/schema.js
asset/set_key/processor.js
asset/set_key/schema.js
asset/sort/processor.js
asset/sort/schema.js
asset/window/processor.js
asset/window/schema.js
test/accumulate-spec.js
test/accumulate_by_key-spec.js
test/data_window_to_array-spec.js
test/dedup_by-spec.js
test/group_by-spec.js
test/remove_key-spec.js
test/set_key-spec.js
test/sort-spec.js
test/window-spec.js

* added processors window, sort, dedup_by (common processor has a dedup), group_by set_key
* accumulate always returns a data window
* expanded tests
* bumped version

window, sort, dedup_on, set_key, group_by processors

---

package.json
yarn.lock

sort-spec.js fails without timsort installed,  so I added the timsort dependency

add timsort

---

.travis.yml
asset/package.json
asset/yarn.lock
package.json
yarn.lock

- Fix NPM registry that was pointing to an interal registry
- Add .travis.yml
- Update dependencies

Fix NPM registry issue and sync repo

---

.travis.yml
asset/asset.json
asset/package.json
package.json

Add node 12 builds to CI
Ref: https://github.com/terascope/teraslice/issues/1500

v0.3.1 - Use node 12 in ci

---

asset/asset.json
asset/package.json
asset/src/routed_sender/processor.ts
asset/src/routed_sender/schema.ts
package.json
test/fixtures/test_api/api.ts
test/fixtures/test_api/test_sender.ts
test/routed_sender-spec.ts
yarn.lock

- fixed routed-sender to work with new api model

Routed sender fixes

---

.yarnclean
asset/asset.json
asset/package.json
package.json
yarn.lock

* updated ts-transforms to 0.49.2 for routable ip fix
*  bumped asset to 0.10.4
* was erring out on coverage report after test, which looked to be related to [this issue](https://github.com/gotwarlost/istanbul/issues/743), so added a line to .yarnclean file

update to ts-transforms

---

asset/asset.json
asset/package.json
package.json
yarn.lock

* updated ts-transforms to v0.51.2
* other module updates

updated dependencies

---

asset/asset.json
asset/package.json
package.json
yarn.lock

* package upgrades to include changes to ts-transforms/ data-mate
* bumped version to 0.10.7

update to packages, ts-transforms/ data-mate

---

asset/src/index.ts

This adds an asset registry to the standard assets.

add asset registry

---

.travis.yml
asset/asset.json
asset/package.json
package.json
tsconfig.json

This adds node 14 and removes node 10 from the supported versions.

add node 14 remove node 10

---

asset/asset.json
asset/package.json
asset/src/index.ts
asset/src/job_metric_api/api.ts
asset/src/job_metric_api/exporter.ts
asset/src/job_metric_api/interfaces.ts
asset/src/job_metric_api/schema.ts
package.json
test/fixtures/job_metric_example/interfaces.ts
test/fixtures/job_metric_example/processor.ts
test/fixtures/job_metric_example/schema.ts
test/job_metric_api/api-no-def-spec.ts
test/job_metric_api/api-spec.ts
test/job_metric_api/schema-spec.ts
yarn.lock

- Added teraslice job metric exporter as `job_metric_api`

added teraslice job metric exporter as job_metric_api

---

package.json

* forgot to bump the top level package.json to 0.12.1

updated top level package.json

---

asset/asset.json
asset/package.json
asset/src/date_router/interfaces.ts
asset/src/date_router/processor.ts
asset/src/date_router/schema.ts
package.json
test/date_router/processor-spec.ts

* added weekly and weekly_epoch resolutions to date_router
* added tests to cover new resolutions
* bumped asset version to 0.12.3

Date router week resolution

---

asset/asset.json
asset/package.json
asset/src/routed_sender/interfaces.ts
asset/src/routed_sender/processor.ts
examples/routed_sender.json
package.json
packages/standard-asset-apis/package.json
packages/standard-asset-apis/src/RoutedSender.ts
packages/standard-asset-apis/src/index.ts
packages/standard-asset-apis/src/routers/DateRouter.ts
packages/standard-asset-apis/test/RoutedSender-spec.ts
packages/standard-asset-apis/test/routers/DateRouter-spec.ts
test/routed_sender/processor-spec.ts

Add RoutedSender to asset apis and hourly date resolution

---

asset/asset.json
asset/package.json
package.json
packages/standard-asset-apis/package.json
packages/standard-asset-apis/src/RoutedSender.ts
packages/standard-asset-apis/test/RoutedSender-spec.ts
test/fixtures/someAssetId/test_api/test_sender.ts
test/match/processor-spec.ts
yarn.lock

Improvements to the routed sender for performance and usability

Improvements to RoutedSender

---

asset/asset.json
asset/package.json
asset/src/add_short_id/interfaces.ts
asset/src/add_short_id/processor.ts
asset/src/add_short_id/schema.ts
docs/operations/add_short_id.md
package.json
test/add_short_id/processor-spec.ts
test/add_short_id/schema-spec.ts
yarn.lock

* new processor add_short_id and tests
* bumped asset version

processor add_short_id

---

asset/asset.json
asset/package.json
asset/src/add_short_id/processor.ts
asset/src/index.ts
package.json
test/index-spec.ts

* added add_short_id processor to index.ts
* added test for index.ts
* bumped asset version

Add short id to index

---

asset/asset.json
asset/package.json
asset/src/date_router/schema.ts
docs/operations/date_router.md
package.json
packages/standard-asset-apis/package.json
packages/standard-asset-apis/src/routers/DateRouter.ts
packages/standard-asset-apis/test/routers/DateRouter-spec.ts
test/date_router/processor-spec.ts
test/routed_sender/processor-spec.ts
yarn.lock

* added config property `use_clock_time` for date_router to use system time instead of a field value on the incoming records
* bumped versions

System time option

---

asset/asset.json
asset/package.json
asset/src/add_key/processor.ts
package.json
test/add_key/processor-spec.ts

* add_key uses our internal setPrecision to truncate floats
* added tests
* bumped asset version

add_key processor truncate fix

---

.github/dependabot.yml

Inside the `dependabot.yml` file I added **sotojn** and **busma13** to the assignees list.

Add Joseph and peter to assignees

---

yarn.lock

├─ @types/json2csv@5.0.4
├─ @types/node-gzip@1.1.1
├─ @types/node@18.18.0
├─ @types/timsort@0.3.1
├─ axios@1.5.1
├─ eslint@8.50.0
└─ tslib@2.6.2

Package upgrades

---

asset/asset.json
asset/package.json
package.json

bump: (patch) standard@0.22.2, standard-assets-bundle@0.22.2

Bump standard asset version

---

package.json
yarn.lock

@terascope/eslint-config: from 0.7.1 to 0.8.0
@terascope/scripts: from 0.59.0 to 0.60.1

Bump eslint-config and scripts packages.

---

.github/workflows/build-and-publish-asset.yml
.github/workflows/test-asset.yml

I have updated both `build-and-publish-asset.yaml` and `test-asset.yaml` to use the current workflow.

Update urls in yaml files to use current workflow

---

asset/package.json
package.json
packages/standard-asset-apis/package.json
yarn.lock

job-components from 0.66.0 to 0.67.0
utils from 0.53.0 to 0.54.0
ts-transforms from 0.79.1 to 0.80.0

upgrade job-components , utils, ts-transforms

---

asset/asset.json
asset/package.json
package.json

bump to re-sync package.json version to release version

bump: (patch) standard@0.23.1, standard-assets-bundle@0.23.1

---

asset/package.json
package.json
packages/standard-asset-apis/package.json
yarn.lock

utils to 0.55.0
job-components to 0.68.0
ts-transforms to 0.81.0
scripts to 0.72.0
express to 4.18.3

Bundled dependency update

---

asset/package.json
package.json
packages/standard-asset-apis/package.json
yarn.lock

- @terascope/job-components from 0.69.0 to 0.70.0
- @terascope/scripts from 0.73.0 to 0.75.0
- @terscope/utils from 0.56.0 to 0.57.0
- ts-transforms from 0.82.0 to 0.83.1

bundled dependency updates

---

.github/workflows/build-and-publish-asset.yml
.github/workflows/test-asset.yml

Use the new terascope/workflows workflow that uploads asset artifacts after tests run.

[CI] use test workflow that uploads asset artifacts
